version: "3"

services:
  # frontend:
  #   image: javascript-img
  #   build: 
  #     context:  
  #     dockerfile:  ./backend/dev.Dockerfile
  #   ports: 
  #     3000:3000
  #   env:
  #     GOOGLE_API_TOKEN=token-value
  backend:
    container_name: python-service
    image: python-img
    build: 
      context: ./backend
      dockerfile:  dev.Dockerfile
    ports:
      - 5000:5000
    restart: always
    
    